# Generated by Django 3.2.7 on 2022-10-23 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobseekerprofile',
            options={'verbose_name': 'Профиль соискателя', 'verbose_name_plural': 'Профиль соискателей'},
        ),
        migrations.AlterModelOptions(
            name='jobseekerrequests',
            options={'verbose_name': 'Запрос соискателя', 'verbose_name_plural': 'Запросы соискателя'},
        ),
        migrations.AlterModelOptions(
            name='jobseekersavejob',
            options={'verbose_name': 'Сохраненная вакансия', 'verbose_name_plural': 'Сохраненные вакансии'},
        ),
        migrations.AlterField(
            model_name='jobseekerrequests',
            name='status',
            field=models.CharField(default='Ожидание встречи с работодателем', max_length=80),
        ),
    ]
