# Generated by Django 3.2.7 on 2022-10-22 10:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0003_alter_job_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 22, 14, 5, 25, 972903)),
        ),
    ]
