# Generated by Django 3.2.7 on 2022-10-23 20:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0004_alter_job_created_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Компания', 'verbose_name_plural': 'Компании'},
        ),
        migrations.AlterModelOptions(
            name='job',
            options={'verbose_name': 'Вакансия', 'verbose_name_plural': 'Вакансии'},
        ),
        migrations.AlterModelOptions(
            name='jobrequests',
            options={'verbose_name': 'Запрос на вакансию', 'verbose_name_plural': 'Запросы на вакансию'},
        ),
        migrations.RemoveField(
            model_name='job',
            name='gender',
        ),
        migrations.AlterField(
            model_name='job',
            name='cooperation_type',
            field=models.CharField(choices=[('Полная занятость', 'Полная занятость'), ('Частичная занятость', 'Частичная занятость'), ('Удаленная работа', 'Удаленная работа'), ('Стажировка', 'Стажировка')], max_length=80),
        ),
        migrations.AlterField(
            model_name='job',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 24, 2, 0, 0, 107241)),
        ),
        migrations.AlterField(
            model_name='job',
            name='degree',
            field=models.CharField(choices=[('Нет высшего образования', 'Нет высшего образования'), ('Диплом бакалавра', 'Диплом бакалавра'), ('Диплом магистра', 'Диплом магистра'), ('Диплом Phd', 'Диплом Phd')], max_length=80),
        ),
        migrations.AlterField(
            model_name='job',
            name='experience',
            field=models.CharField(choices=[('Нет опыта работы', 'Нет опыта работы'), ('1-3 года', '1-3 года'), ('3-6 года', '3-6 года'), ('6 и выше', '6 и выше')], max_length=80),
        ),
        migrations.AlterField(
            model_name='job',
            name='military_service',
            field=models.CharField(choices=[('Военнообязанный', 'Военнообязанный'), ('Есть военный билет', 'Есть военный билет')], max_length=80),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary',
            field=models.CharField(choices=[('По соглашению с двух сторон', 'По соглашению с двух сторон'), ('от 100 000 до 190 000 тг.', 'от 100 000 до 190 000 тг.'), ('от 200 000 до 290 000 тг.', 'от 200 000 до 290 000 тг.'), ('от 300 000 до 390 000 тг.', 'от 300 000 до 390 000 тг.'), ('от 400 000 до 490 000 тг.', 'от 400 000 до 490 000 тг.'), ('от 500 000 и выше', 'от 500 000 и выше')], max_length=80),
        ),
    ]
