# Generated by Django 3.2.7 on 2022-10-24 07:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0005_auto_20221024_0200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='military_service',
        ),
        migrations.AlterField(
            model_name='job',
            name='cooperation_type',
            field=models.CharField(choices=[('Полная занятость', 'Полная занятость'), ('Частичная занятость', 'Частичная занятость'), ('Удаленная работа', 'Удаленная работа'), ('Стажировка', 'Стажировка'), ('Производственная практика', 'Производственная практика')], max_length=80),
        ),
        migrations.AlterField(
            model_name='job',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 24, 13, 12, 2, 205966)),
        ),
        migrations.AlterField(
            model_name='job',
            name='degree',
            field=models.CharField(choices=[('Не имеет значения', 'Не имеет значения'), ('Диплом ТиПО', 'Диплом ТиПО'), ('Диплом бакалавра', 'Диплом бакалавра'), ('Диплом магистра', 'Диплом магистра'), ('Диплом Phd', 'Диплом Phd')], max_length=80),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary',
            field=models.CharField(choices=[('Не указано', 'Не указано'), ('от 100 000 до 190 000 тг.', 'от 100 000 до 190 000 тг.'), ('от 200 000 до 290 000 тг.', 'от 200 000 до 290 000 тг.'), ('от 300 000 до 390 000 тг.', 'от 300 000 до 390 000 тг.'), ('от 400 000 до 490 000 тг.', 'от 400 000 до 490 000 тг.'), ('от 500 000 и выше', 'от 500 000 и выше')], max_length=80),
        ),
    ]
