# Generated by Django 3.2.7 on 2023-10-05 04:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0006_auto_20221024_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 10, 5, 10, 12, 28, 682806)),
        ),
    ]
