# Generated by Django 3.2.7 on 2023-10-10 09:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0007_alter_job_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 10, 10, 15, 40, 19, 52600)),
        ),
        migrations.AlterField(
            model_name='jobrequests',
            name='accepted',
            field=models.BooleanField(),
        ),
    ]
