# Generated by Django 3.2.7 on 2023-10-10 12:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0008_auto_20231010_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 10, 10, 18, 18, 29, 216945)),
        ),
        migrations.AlterField(
            model_name='jobrequests',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
