# Generated by Django 5.0.4 on 2024-04-28 18:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employer", "0009_auto_20231010_1818"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="created_date",
            field=models.DateTimeField(
                blank=True, default=datetime.datetime(2024, 4, 28, 23, 49, 1, 582298)
            ),
        ),
    ]
