# Generated by Django 5.0.4 on 2024-04-29 18:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0010_alter_job_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 4, 29, 23, 15, 41, 938768)),
        ),
    ]
